export const SET_CATALOG = 'SET_CATALOG';
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';
export const SET_LOGIN = "SET_LOGIN";
export const SET_CART_PRODUCTS = "SET_CART_PRODUCTS";
export const DELETE_CART_PRODUCT = "DELETE_CART_PRODUCT";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_FILTERS = "SET_FILTERS";
export const SET_ALL_COLORS = "SET_ALL_COLORS";